version: '3.7'

services:

  app:
    container_name: branch_frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3001
    environment:
      - CHOKIDAR_USEPOLLING=true